services:
  bot:
#    container_name: podcastie-bot
    build:
      context: .
      dockerfile: ./services/bot/Dockerfile

    secrets:
      - telegram_bot_token
      - mongo_database

    environment:
      BOT_TELEGRAM_BOT_TOKEN_FILE: /run/secrets/telegram_bot_token

      BOT_MONGO_HOST: mongo
      BOT_MONGO_PORT: 27017
      BOT_MONGO_DATABASE_FILE: /run/secrets/mongo_database

    depends_on:
      - mongo

    restart: unless-stopped

  feed_poller:
#    container_name: podcastie-feed_poller
    build:
      context: .
      dockerfile: ./services/feed_poller/Dockerfile

    secrets:
      - telegram_bot_token
      - mongo_database

    environment:
      FEED_POLLER_INTERVAL: 5
      FEED_POLLER_TELEGRAM_BOT_API_HOST: telegram-bot-api
      FEED_POLLER_TELEGRAM_BOT_API_PORT: 8081

      FEED_POLLER_TELEGRAM_BOT_TOKEN_FILE: /run/secrets/telegram_bot_token

      FEED_POLLER_MONGO_HOST: mongo
      FEED_POLLER_MONGO_PORT: 27017
      FEED_POLLER_MONGO_DATABASE_FILE: /run/secrets/mongo_database

    depends_on:
      - mongo
      - telegram-bot-api

    restart: unless-stopped

  telegram-bot-api:
#    container_name: podcastie-telegram-bot-api
    build: ../telegram-bot-api

    secrets:
      - telegram_api_id
      - telegram_api_hash

    environment:
      TELEGRAM_API_ID_FILE: /run/secrets/telegram_api_id
      TELEGRAM_API_HASH_FILE: /run/secrets/telegram_api_hash

  mongo:
#    container_name: podcastie-mongo
    hostname: mongo
    image: mongo
    volumes:
      - ./services/mongo:/data/db

    secrets:
      - mongo_database

    environment:
      MONGO_INITDB_DATABASE_FILE: /run/secrets/mongo_database

    ports:
      - "27017:27017"

    restart: unless-stopped

secrets:
  telegram_bot_token:
    file: ./.secrets/telegram_bot_token

  mongo_database:
    file: ./.secrets/mongo_database

  telegram_api_id:
    file: ./secrets/telegram_api_id

  telegram_api_hash:
    file: ./secrets/telegram_api_hash
