services:
  bot:
    build:
      context: ./services/bot
    secrets:
      - bot_token
      - mongo_user
      - mongo_password
      - mongo_database
    environment:
      BOT_TOKEN_FILE: /run/secrets/bot_token

  notifier:
    build:
      context: ./services/notifier
    secrets:
      - bot_token
      - mongo_user
      - mongo_password
      - mongo_database

  mongo:
    image: mongo
    volumes:
      - ./services/mongo:/data/db
    secrets:
      - mongo_user
      - mongo_password
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
      MONGO_INITDB_DATABASE_FILE: /run/secrets/mongo_database

secrets:
  bot_token:
    file: ./secrets/bot_token
  mongo_user:
    file: ./secrets/mongo_user
  mongo_password:
    file: ./secrets/mongo_password
  mongo_database:
    file: ./secrets/mongo_database